DROP TABLE IF EXISTS students;

CREATE TABLE students (
	serial_id	SERIAL PRIMARY KEY,
	inter_dom	TEXT,
	region		TEXT,
	gender		TEXT,
	academic	TEXT,
	age		INTEGER,
	age_cate	INTEGER,
	stay		INTEGER,
	stay_cate	TEXT,
	japanese	INTEGER,
	japanese_cate	TEXT,
	english		INTEGER,
	english_cate	TEXT,
	intimate	TEXT,
	religion	TEXT,
	suicide		TEXT,
	dep		TEXT,
	deptype		TEXT,
	todep		INTEGER,
	depsev		TEXT,
	tosc		INTEGER,
	apd		INTEGER,
	ahome		INTEGER,
	aph		INTEGER,
	afear		INTEGER,
	acs		INTEGER,
	aguilt		INTEGER,
	amiscell	INTEGER,
	toas		INTEGER,
	partner		INTEGER,
	friends		INTEGER,
	parents		INTEGER,
	relative	INTEGER,
	profess		INTEGER,
	phone		INTEGER,
	doctor		INTEGER,
	reli		INTEGER,
	alone		INTEGER,
	others		INTEGER,
	internet	TEXT,
	partner_bi	TEXT,
	friends_bi	TEXT,
	parents_bi	TEXT,
	relative_bi	TEXT,
	professional_bi	TEXT,
	phone_bi	TEXT,
	doctor_bi	TEXT,
	religion_bi	TEXT,
	alone_bi	TEXT,
	others_bi	TEXT,
	internet_bi	TEXT
);
